stages:
  data_ingestion:
    cmd: python src/reviewAnalysis/pipeline/stage_01_data_ingestion.py
    deps:
      - src/reviewAnalysis/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/flipkart.csv

  data_validation:
    cmd: python src/reviewAnalysis/pipeline/stage_02_data_validation.py
    deps:
      - src/reviewAnalysis/pipeline/stage_02_data_validation.py
      - config/config.yaml
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/reviewAnalysis/pipeline/stage_03_data_transformation.py
    deps:
      - src/reviewAnalysis/pipeline/stage_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/main_df.csv

  model_trainer:
    cmd: python src/reviewAnalysis/pipeline/stage_04_model_trainer.py
    deps:
      - src/reviewAnalysis/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/flipkart.csv
      - artifacts/data_validation
      - artifacts/data_transformation
    params:
      - TrainingArguments
    outs:
      - artifacts/model_trainer/tokenizer.pickle 
      - artifacts/model_trainer/model.h5
      - src/reviewAnalysis/models/model.h5

        